BEGIN TRANSACTION;

COPY AllStarFull FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/AllstarFull.csv' WITH CSV HEADER DELIMITER AS ',';
COPY Appearances FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/Appearances.csv' WITH CSV HEADER DELIMITER AS ',';
COPY AwardsManagers FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/AwardsManagers.csv' WITH CSV HEADER DELIMITER AS ',';
COPY AwardsPlayers FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/AwardsPlayers.csv' WITH CSV HEADER DELIMITER AS ',';
COPY AwardsShareManagers FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/AwardsShareManagers.csv' WITH CSV HEADER DELIMITER AS ',';
COPY AwardsSharePlayers FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/AwardsSharePlayers.csv' WITH CSV HEADER DELIMITER AS ',';
COPY Batting FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/Batting.csv' WITH CSV HEADER DELIMITER AS ',';
COPY BattingPost FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/BattingPost.csv' WITH CSV HEADER DELIMITER AS ',';
COPY CollegePlaying FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/CollegePlaying.csv' WITH CSV HEADER DELIMITER AS ',';
COPY Fielding FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/Fielding.csv' WITH CSV HEADER DELIMITER AS ',';
COPY FieldingOF FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/FieldingOF.csv' WITH CSV HEADER DELIMITER AS ',';
COPY FieldingPost FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/FieldingPost.csv' WITH CSV HEADER DELIMITER AS ',';
COPY FieldingOFsplit FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/FieldingOFsplit.csv' WITH CSV HEADER DELIMITER AS ',';
COPY HallOfFame FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/HallOfFame.csv' WITH CSV HEADER DELIMITER AS ',';
COPY HomeGames FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/HomeGames.csv' WITH CSV HEADER DELIMITER AS ',';
COPY Managers FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/Managers.csv' WITH CSV HEADER DELIMITER AS ',';
COPY ManagersHalf FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/ManagersHalf.csv' WITH CSV HEADER DELIMITER AS ',';
COPY Master FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/Master.csv' WITH CSV HEADER DELIMITER AS ',';
COPY Parks FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/Parks.csv' WITH CSV HEADER DELIMITER AS ',';
COPY Pitching FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/Pitching.csv' WITH CSV HEADER DELIMITER AS ',';
COPY PitchingPost FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/PitchingPost.csv' WITH CSV HEADER DELIMITER AS ',';
COPY Salaries FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/Salaries.csv' WITH CSV HEADER DELIMITER AS ',';
COPY Schools FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/Schools.csv' WITH CSV HEADER DELIMITER AS ',';
COPY SeriesPost FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/SeriesPost.csv' WITH CSV HEADER DELIMITER AS ',';
COPY Teams FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/Teams.csv' WITH CSV HEADER DELIMITER AS ',';
COPY TeamsFranchises FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/TeamsFranchises.csv' WITH CSV HEADER DELIMITER AS ',';
COPY TeamsHalf FROM '/Users/michaelaltamirano/documents/app_academy/~JobSearch/2016baseballstats/project/csv/TeamsHalf.csv' WITH CSV HEADER DELIMITER AS ',';

END TRANSACTION;
